### ISSUE TITLE
Getevent error

### ISSUE THREAD

**Issue by elvispoz** [DaWe35/Facebook-event-crawler#4] opened 2020-07-06 07:45 UTC
> Getevent error
ERROR:root:message
Traceback (most recent call last):
  File "C:\Crawlr.py", line 113, in getevent
    datefrom = timestring.Date(splitted[0]).date
  File "C:\Users\abc\AppData\Local\Programs\Python\Python37-32\lib\site-packages\timestring\Date.py", line 176, in __init__
    new_date = new_date.replace(hour=int(max(hour)))
ValueError: hour must be in 0..23

Error, writing del.html...

**Comment by DaWe35** [comment] 2020-07-06 19:40
Hey @elvispoz , thatks for the report. Can you send me the del.html file? Facebbok haschanged something and I need to look into.

**Comment by elvispoz** [comment] 2020-07-07 06:49
@DaWe35 of course. Please give your email.

**Comment by DaWe35** [comment] 2020-07-15 11:39
The event what we are talking about: https://www.facebook.com/events/1419266971566473
@elvispoz I looked into the HTML page what you sent, and it does not contain event description so that's why the script was unable to read it. However, I logged in to facebook and there was description. Weird.

**Comment by DaWe35** [comment] 2020-07-15 11:46
Yepp, it worked with my FB account. I recommend you to open the mobile site https://mobile.facebook.com/events/1419266971566473 with the crawler account, so you can check where the description is.
![kép](https://user-images.githubusercontent.com/10603822/87541369-6c771800-c6a1-11ea-97fe-cbf20018ab93.png)

**Comment by elvispoz** [comment] 2020-07-16 18:04
Did you see the same source code in the event?
![1419266971566473](https://user-images.githubusercontent.com/65545654/87706264-81d26c00-c79f-11ea-810f-5775ada89892.png)

**Comment by DaWe35** [comment] 2020-07-29 09:06
Closing, because a duplicate of #3

**Closed by DaWe35** 2020-07-29 09:06 UTC
